# Generated by Django 3.1.7 on 2021-10-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(choices=[('Paradise', 'Paradise'), ('Park Hyatt', 'Park Hyatt'), ('Mariott', 'Mariott'), ('Radisson', 'Radisson'), ('Novotel', 'Novotel'), ('Hyatt Place', 'Hyatt Place')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attendies', models.IntegerField(blank=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
